server:
    port: 5213
    servlet:
      context-path: /${spring.application.name}

spring:
    application: 
        name: attemper-interior
    profiles:
        active: dev

# eureka
eureka:
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application_instance_id:${random.value}}
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    region: default
    availabilityZones:
      default: defaultZone
    preferSameZone: false