eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

dispatch:
  user-name: interior
  password: LR6sWNFAPIfZgYIUX+u9fY4qsNlQR0H4QqPEuyLRBm8=
  executor:
    service-name: attemper-executor
